#!/usr/bin/env bash
# This script displays numbers from 1 to 100
# Displays Fizz for multiples of 3, Buzz for multiples of 5
# Displays FizzBuzz for multiples of both 3 and 5

count=1
while [ $count -le 100 ]; do
    if [ $((count % 15)) -eq 0 ]; then
        echo "FizzBuzz"
    elif [ $((count % 3)) -eq 0 ]; then
        echo "Fizz"
    elif [ $((count % 5)) -eq 0 ]; then
        echo "Buzz"
    else
        echo "$count"
    fi
    count=$((count + 1))
done

