#!/usr/bin/env bash
# Displays "To infinity and beyond" indefinitely and reacts to SIGTERM

# Trap SIGTERM and print message instead of exiting
trap 'echo "I am invincible!!!"' SIGTERM

while true; do
    echo "To infinity and beyond"
    sleep 2
done

